### ISSUE TITLE
Can't use go-config beyond version 0.7.0

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/cert-operator#15]
## Descriptio of Issue

After [go-config](https://github.com/micro/go-config) v0.7.0, our operator breaks on startup citing that there is no provider configured.

## How to Reproduce

Update the following constraint in `Gopkg.toml` from `0.7.0` to any later release:
```
[[constraint]]
  name = "github.com/micro/go-config"
  version = "0.7.0"
```

Install dependencies and start operator:
```
dep ensure
operator-sdk up local
```

## Expected result

Operator starts successfully

## Actual Result

```
panic: There was a problem detecting which provider to configure. 
	Provider kind `` is invalid. 
{"provider":{"kind":""},"general":{"annotations":{"status":"","status-reason":"","expiry":"","format":""}}}

goroutine 1 [running]:
github.com/redhat-cop/cert-operator/pkg/stub.NewHandler(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/esauer/go/src/github.com/redhat-cop/cert-operator/pkg/stub/handler.go:32 +0x30e
main.main()
	/home/esauer/go/src/github.com/redhat-cop/cert-operator/cmd/cert-operator/main.go:33 +0x177
exit status 2
Error: failed to run operator locally: exit status 1
```

**Comment by AdlerFleurant** [comment]
The version of go-config being used at this point is v1.1.0. Shouldn't we close this issue now? @etsauer

**Comment by etsauer** [comment]
@AdlerFleurant yes we can close, but can you first add a reference to the PR that resolved it?
